#
# A docker compose file to spin up a mysql database and run the api with it
# Used for development
#

version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
  api:
    image: openlab.ncl.ac.uk:4567/poster-vote/node-backend:1.4.0
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: .env.api.local
    environment:
      NODE_ENV: development
      DB_TYPE: mysql
      DB_URI: mysql://root:secret@mysql/postervote
      JWT_SECRET: super_duper_secret
      COOKIE_SECRET: really_really_secret
      HASH_SECRET: another_really_secret_secret
      ADMIN_EMAIL: postervote@openlab.ncl.ac.uk
      REG_TWILIO_NUMBER: 07880 123 456
      VOTE_TWILIO_NUMBER: 07880 654 321
    
